### ISSUE TITLE
Plugin publication

### ISSUE THREAD

**Issue by vialcollet** [huseyz/obsidian-wallabag#1]
Hi
Fantastic work with this plugin. Thanks a lot.
I am so happy I could find it.

One question, why not publishing it? It is so greazt and useful.

Let me know if you need any help.

**Comment by MisterPresident** [comment]
+1

**Comment by legolasdimir** [comment]
+1

**Comment by MisterPresident** [comment]
+1

**Comment by huseyz** [comment]
I thought at most 3 people would be interested, but it got a bit more attention that I expected; I will check the publication process and if it's not too much work; I will try.
