### ISSUE TITLE
Mobile App Support

### ISSUE THREAD

**Issue by joebetsill** [huseyz/obsidian-wallabag#14]
Does this plugin support the obsidian mobile app? I doesn't seem to work for me on mobile (android). Desktop (linux) works fine. Is there something more I need to do to get it working on mobile?

Thanks!

**Comment by huseyz** [comment]
Hi @joebetsill 

Thanks for the heads-up; looks like it was broken. I attempted to fix it with the last release; let me know if it doesn't work after updating.
