### ISSUE TITLE
Zip/docu is missing plugin folder

### ISSUE THREAD

**Issue by chymian** [huseyz/obsidian-wallabag#17]
hi, 
when following your installation instructions, the files get unzip in the wrong folder: 

> - Extract the files in your vault's plugins folder: `[VAULT]/.obsidian/plugins/`

there is no sub-folder for the plugin, neither mentioned in the docs nor in the zip, so it extracts the files directly into `.obsidian/plugins/` and one has to create the `obsidian-wallabag` and move files manualy.

BTW: can you please remove these Apple-leftovers from your ZIP-Archive.
they are ugly clutter on any other system.

```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2023-06-27 03:50:34 .....          313          193  manifest.json
2023-06-27 03:50:34 .....          163           84  __MACOSX/._manifest.json
2023-06-27 03:51:47 .....        21148         5024  main.js
2023-06-27 03:51:47 .....          163           84  __MACOSX/._main.js
------------------- ----- ------------ ------------  ------------------------
```

**Comment by huseyz** [comment]
Good point; I will update the zip and the readme next time

**Comment by huseyz** [comment]
Added folder in the zip.
