### ISSUE TITLE
authentication does not work

### ISSUE THREAD

**Issue by fstelte** [huseyz/obsidian-wallabag#2]
I have installed the plugin manually, can enable it, but authentication does not work.

Details:
MacOS Venture 13.1
Obsidian 1.1.9

**Comment by huseyz** [comment]
Can you give some more details? Does it just fail to authenticate, or something else? Also double-check your server url and username, my instance requires you to input your email there.
Also do you mind checking if there is any helpful logs in the js console while authenticating; you can open it by Command+option+i before going in to the settings.

**Comment by fstelte** [comment]
When I hit authenticate it just does not do anything. When closing the plugin configuration, everything I entered for the authentication is gone again.

![image](https://user-images.githubusercontent.com/28839439/215345861-d774cab7-7063-4596-bf44-5a4a12d0fd40.png)

**Comment by huseyz** [comment]
Have you tried using your email instead of username?

**Comment by fstelte** [comment]
Yes I did

**Comment by fstelte** [comment]
I used the console (sorry for the late reaction) but when I hit the authenticate button, nothing happens..

**Comment by chymian** [comment]
hi, 
I see the same problem:

WS: linux debian bullseye
obsidian: 1.3.5
wallabag: 2.5.4, running on cloudron.io 

Login with email & pw.


this is logged on the console:
```log
Error: Request failed, status 404
    at new t (app.js:1:1719205)
    at $U (app.js:1:1719397)
    at app.js:1:1720074
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
```

this is logged on the server:
```log
Jun 07 18:58:24 183.182.115.1 - - [07/Jun/2023:11:58:24 +0000] "POST //oauth/v2/token HTTP/1.1" 404 471 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/1.3.5 Chrome/112.0.5615.183 Electron/24.3.1 Safari/537.36"
```

**Comment by huseyz** [comment]
@chymian 

Make sure you don't have a trailing slash `/` in your Server URL. Log indicates there is one

**Comment by chymian** [comment]
@huseyz 
sry for late reply, been away.

updateted the plugin to 0.1.4:
Obsidian flatpak is 1.3.5
OS is bookworm.

state:
w/o trailing slash, doesn't make any difference.

**Comment by gwutz** [comment]
Had the same problem and I looked a bit into the code. I am not super sure but my password contained a '&' character and therefore the form parameters are malformed. I was able to fix it via sending it as json. If you want I can provide a MR - for me this works.

**Comment by gwutz** [comment]
@fstelte if you are interested - i made the MR https://github.com/huseyz/obsidian-wallabag/pull/19#issue-1822735313

**Comment by huseyz** [comment]
Nice catch!

**Comment by huseyz** [comment]
Closing this since #19 fixes it; reopen if needed
