### ISSUE TITLE
Sync not working after newest wallabag update

### ISSUE THREAD

**Issue by legolasdimir** [huseyz/obsidian-wallabag#28]
I tried to resync my articles after the last update and nothing is coming through. The plugin is set to sync at startup and I tried just doing archived first. I get this in the console

![image](https://github.com/huseyz/obsidian-wallabag/assets/21345773/ef01cfcd-4a47-432a-96c9-629fa27bcdab)

**Comment by legolasdimir** [comment]
According to obsidian the plugin is successfully authenticated.

**Comment by legolasdimir** [comment]
Im also getting messages that the plugin cant find the article template file even though it has not moved. I reinstalled the plugin and it synced a couple of times then I got that message.
![image](https://github.com/huseyz/obsidian-wallabag/assets/21345773/577e393c-33a3-439e-a9d8-c3416183e52f)

**Comment by huseyz** [comment]
Interesting. First error looks like an issue from wallabag side; unfortunately it's not possible to print error bodies becuase of the obsidian API so maybe you might see something in your server logs.
For the second one, unfortunately, I have no way of testing it on Windows; let me know if you find any leads, I will do my best to mitigate.

**Comment by legolasdimir** [comment]
I can help you test if you tell me what you need. We did to some testing on
our end but saw nothing useful in the logs.

**Comment by huseyz** [comment]
I tried with a Windows 11 VM, and I wasn't able to reproduce the issue; there are a lot of parameters I can't replicate here, so I can't offer much help. If you find any more details, I will do my best.

**Comment by legolasdimir** [comment]
The sync is working now as I mentioned in #31
