### ISSUE TITLE
Cannot update to latest version

### ISSUE THREAD

**Issue by legolasdimir** [huseyz/obsidian-wallabag#30]
I cannot update this plugin's latest version using BRAT or the Obsidian store. I had some people in the discord look and it looks like the manifest wasn't updated.

**Comment by legolasdimir** [comment]
one of the obsidian team said that the manifest that needs updating is the one at the root of the repo

**Comment by huseyz** [comment]
Looks like I forgot to push the version bump to master. Fixed it now.
