### ISSUE TITLE
Archive sync no longer works

### ISSUE THREAD

**Issue by legolasdimir** [huseyz/obsidian-wallabag#31]
The sync appears to be working again but the toggle to sync archived articles is not working as it once did. Now it is syncing EVERYTHING. I don't know if this is intended or not.

**Comment by jeffbeaulieu** [comment]
@legolasdimir You can read the comment here : https://github.com/huseyz/obsidian-wallabag/pull/29
i'll be working on it soon

**Comment by legolasdimir** [comment]
@jeffbeaulieu thats the behavior I was looking for. Having one toggle that syncs archived articles (yes/no) and a place to specify what directory to put them in and then a separate one for unread. and REALLY another one to specify starred articles? but that's more like nice to have

**Comment by jeffbeaulieu** [comment]
I'll try to add those directories as optional parameters.  But I don't believe there is a mechanism to sync them (move between obsidian directories) once they will have been synced to either directory (unread, archived), than their status changes in Wallabag.

**Comment by legolasdimir** [comment]
@jeffbeaulieu thats fine. basically what I did in mine before was I would sync in all the archived then change the settings and sync all the unread into a different folder then I would manually move the starred items.

So simply being able to pipe them each to their own folder to start would be fine.
