### ISSUE TITLE
Tags not created: Uncaught TypeError: Cannot read properties of null (reading 'frontmatter') { isTrusted: [Getter] }

### ISSUE THREAD

**Issue by dahifi** [huseyz/obsidian-wallabag#34]
Just setting up a hosted install and got articles to import but got this error in the developer log for each record in the import: 

Uncaught TypeError: Cannot read properties of null (reading 'frontmatter') { isTrusted: [Getter] }

Next steps?

**Comment by dahifi** [comment]
Second attempt: changed tags from # to CSV, got same error in console, but the front matter was created with the import, although all tags are prefaced with a `t:` as in `t:first-tag`, `t:second-tag`.

**Comment by huseyz** [comment]
This is now solved in the latest release, please update, try and reopen if it's not working.
