### ISSUE TITLE
Authentication with Wallabag failed

### ISSUE THREAD

**Issue by adrienneteicher** [huseyz/obsidian-wallabag#38]
Hi,

I'm using the hosted wallabag at wallabag.it and when I attempt to set up the Obsidian plugin I get an error message:

"Authentication with Wallabag failed"

When I check the developer tools in Obsidian I can see the following message:

Error: Request failed, status 404
    at new t (app.js:1:2107831)
    at mK (app.js:1:2108023)
    at app.js:1:2108702
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

I tried the following server url both with and without the / at the end: https://app.wallabag.it/

I gave the details from the API client I created as well as my username and password.

Any ideas what I am doing wrong?

Thanks!

**Comment by adrienneteicher** [comment]
Please ignore. It's working now.

**Comment by pauby** [comment]
Just wanted to add to this. The slash at the end kept failing, without the slash I authenticated immediately.

The documentation around this field really needs to be updated.
